import Foundation

/// The derived import-alias table (FER-794): common gym names (es-MX + EN) → native catalog id.
///
/// FER-779 swapped the curated catalog for ExerciseDB OSS — 1500 hyper-specific entries where the
/// *basic* variant of a movement often has no plain name ("press militar de pie" doesn't exist;
/// only 12 suffixed variants do). This table restores the bridge the retired synonym table
/// (FER-522) provided, but derived: it's generated by `Tools/bake-exercisedb/build_aliases.py`
/// (reviewable, re-runnable after a re-bake), never hand-edited here.
///
/// Keys are stored as a person writes them; `WorkoutExerciseReconciler` normalizes them at load,
/// so accents/case never matter. Baked into the bundle — offline, zero network.
public enum ExerciseAliasTable {

    /// alias (as written) → native exercise id. Empty only if the resource is missing/corrupt.
    public static let bundled: [String: String] = load()

    private static func load() -> [String: String] {
        guard let url = Bundle.module.url(forResource: "exercise-aliases", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let map = try? JSONDecoder().decode([String: String].self, from: data)
        else { return [:] }
        return map
    }
}
