#!/usr/bin/env python3
"""Inject German (de) translations into Cenit/Resources/Localizable.xcstrings.

Reads the English (en) base values and adds a `de` stringUnit for each key.
Format placeholders (%@, %lld, %%) are preserved. Pure symbol / placeholder-only
strings are passed through unchanged. Re-runnable: existing `de` units are
overwritten so this file stays the source of truth for the German translation.
"""
import json
from pathlib import Path

CATALOG = Path("Cenit/Resources/Localizable.xcstrings")

# English key -> German value. Keys must match the catalog exactly.
DE: dict[str, str] = {
    # FER-256 — Detalle de Temperatura de la piel (SkinTempDetailScreen)
    "How far last night's skin temperature ran from your own recent baseline, in °C. We learn your normal over recent nights, so 0 is your usual and the number is the shift up or down. A single warm or cool night rarely means much — what's worth noticing is several nights in a row drifting the same way. It's a comfort signal, not a thermometer or a diagnosis.": 'Wie weit deine Hauttemperatur letzte Nacht von deiner eigenen jüngsten Baseline abwich, in °C. Wir lernen dein Normal aus den letzten Nächten, also ist 0 dein Üblich und die Zahl die Verschiebung nach oben oder unten. Eine einzelne warme oder kühle Nacht bedeutet selten viel – worauf es ankommt, sind mehrere Nächte in Folge, die in dieselbe Richtung driften. Es ist ein Komfortsignal, kein Thermometer und keine Diagnose.',
    'Information about skin temperature': 'Informationen zur Hauttemperatur',
    'No skin-temperature reading yet. Wear your strap overnight and open this again after it syncs.': 'Noch keine Hauttemperatur-Messung. Trage dein Band über Nacht und öffne dies erneut, sobald es synchronisiert hat.',
    'Right around your usual nighttime baseline.': 'Genau um deine übliche nächtliche Baseline.',
    'A touch warmer than your baseline last night.': 'Eine Spur wärmer als deine Baseline letzte Nacht.',
    'A touch cooler than your baseline last night.': 'Eine Spur kühler als deine Baseline letzte Nacht.',
    "Each point is one night's deviation from your baseline. The shaded band is your own typical night-to-night swing (±1 SD around 0) — inside it is business as usual; a run of nights poking out the same side is the signal. Average and the range come from the period you pick; the chip compares this month's average with last month's, in °C.": 'Jeder Punkt ist die Abweichung einer Nacht von deiner Baseline. Das schattierte Band ist dein eigenes typisches Schwanken von Nacht zu Nacht (±1 SD um 0) – innerhalb davon ist alles wie gewohnt; mehrere Nächte in Folge, die auf derselben Seite herausragen, sind das Signal. Durchschnitt und Bereich stammen aus dem gewählten Zeitraum; der Chip vergleicht den Durchschnitt dieses Monats mit dem des Vormonats, in °C.',
    'Information about the skin temperature trend': 'Informationen zum Verlauf der Hauttemperatur',
    'The standard deviation of your nightly deviations — how much your skin temperature wanders around your baseline from night to night, in °C. A small number means steady thermoregulation; a larger one means more night-to-night swing. (We show the spread in °C rather than a percentage because the average sits near zero, where a percentage would be meaningless.)': 'Die Standardabweichung deiner nächtlichen Abweichungen – wie stark deine Hauttemperatur von Nacht zu Nacht um deine Baseline schwankt, in °C. Eine kleine Zahl bedeutet stabile Thermoregulation; eine größere mehr Schwankung von Nacht zu Nacht. (Wir zeigen die Streuung in °C statt in Prozent, weil der Durchschnitt nahe null liegt, wo ein Prozentwert bedeutungslos wäre.)',
    'How much your nightly temperature swings around your baseline. Lower is steadier.': 'Wie stark deine nächtliche Temperatur um deine Baseline schwankt. Niedriger ist gleichmäßiger.',
    "Each night your strap records skin temperature. We compare it with a rolling baseline of your own recent nights and report the difference in °C — so the value is always relative to you, not an absolute temperature. The trend and the spread are computed from that same nightly deviation.": 'Jede Nacht zeichnet dein Band die Hauttemperatur auf. Wir vergleichen sie mit einer gleitenden Baseline deiner eigenen jüngsten Nächte und geben die Differenz in °C an – der Wert ist also immer relativ zu dir, keine absolute Temperatur. Verlauf und Streuung werden aus derselben nächtlichen Abweichung berechnet.',
    'Nightly skin-temperature deviation from a personal rolling baseline. A comfort signal, not a thermometer or a diagnosis.': 'Nächtliche Abweichung der Hauttemperatur von einer persönlichen gleitenden Baseline. Ein Komfortsignal, kein Thermometer und keine Diagnose.',
    'Nightly skin-temperature deviation, in degrees Celsius': 'Nächtliche Abweichung der Hauttemperatur, in Grad Celsius',
    # FER-238 — Detalle de Esfuerzo (StrainDetailScreen)
    'All-out day — about as much strain as you carry.': 'Volle Pulle – fast so viel Belastung, wie du verträgst.',
    "Day Strain is your cardiovascular load on a 0–21 scale. Each second your heart rate is recorded, it's placed in an intensity zone (1–5); higher zones weigh more, and the total is compressed logarithmically so 21 is a theoretical maximum — a full day at peak intensity. (Edwards 1993; Banister 1991)": 'Day Strain ist deine kardiovaskuläre Belastung auf einer Skala von 0–21. Jede Sekunde, in der deine Herzfrequenz erfasst wird, wird einer Intensitätszone (1–5) zugeordnet; höhere Zonen zählen mehr, und die Summe wird logarithmisch komprimiert, sodass 21 ein theoretisches Maximum ist – ein ganzer Tag bei Höchstintensität. (Edwards 1993; Banister 1991)',
    'Day strain, 7-day moving average': 'Day Strain, gleitender 7-Tage-Durchschnitt',
    'Each second of heart rate is mapped to one of five intensity zones; time in the higher zones counts for much more. The weighted total is compressed onto a 0–21 scale through a logarithmic curve, so the top of the scale represents a theoretical full day at peak intensity.': 'Jede Sekunde der Herzfrequenz wird einer von fünf Intensitätszonen zugeordnet; Zeit in den höheren Zonen zählt deutlich mehr. Die gewichtete Summe wird über eine logarithmische Kurve auf eine Skala von 0–21 komprimiert, sodass das obere Ende einen theoretischen ganzen Tag bei Höchstintensität darstellt.',
    'Hard effort today — solid work.': 'Harte Anstrengung heute – starke Arbeit.',
    'Heart-rate-zone load (TRIMP), compressed logarithmically. (Edwards 1993; Banister 1991)': 'Belastung nach Herzfrequenzzonen (TRIMP), logarithmisch komprimiert. (Edwards 1993; Banister 1991)',
    'Information about day strain': 'Informationen zum Day Strain',
    "Information about how today's strain added up": 'Informationen dazu, wie sich deine Belastung heute summiert hat',
    'Information about the strain zones': 'Informationen zu den Belastungszonen',
    'Light load today — plenty left in the tank.': 'Leichte Belastung heute – noch viel im Tank.',
    'Moderate effort today.': 'Moderate Anstrengung heute.',
    'No strain from today yet — your recent history is below.': 'Noch keine Belastung von heute – dein bisheriger Verlauf steht unten.',
    'No strain yet. Wear your strap through the day and open this again after it syncs.': 'Noch keine Belastung. Trage deine Band über den Tag und öffne dies erneut, sobald sie synchronisiert.',
    "The line is your 7-day moving average over the period you pick. The percentage compares this month's average with last month's. Average, Lowest and Highest come from the range you selected.": 'Die Linie ist dein gleitender 7-Tage-Durchschnitt über den gewählten Zeitraum. Der Prozentwert vergleicht den Durchschnitt dieses Monats mit dem des Vormonats. Durchschnitt, Tiefst- und Höchstwert stammen aus dem gewählten Bereich.',
    "The line shows how your strain piled up through the day — each second of heart rate adds to the running total, so it only ever rises. It ends on today's score above.": 'Die Linie zeigt, wie sich deine Belastung über den Tag aufgebaut hat – jede Sekunde Herzfrequenz zählt zur laufenden Summe, daher steigt sie nur. Sie endet bei deinem heutigen Wert oben.',
    "Your heart rate falls into one of four intensity zones through the day. The highlighted row is where today's score lands on the 0–21 scale.": 'Deine Herzfrequenz fällt über den Tag in eine von vier Intensitätszonen. Die hervorgehobene Zeile zeigt, wo dein heutiger Wert auf der Skala von 0–21 liegt.',
    'Zones': 'Zonen',
    # FER-235 — calendario táctil
    'no reading': 'keine Messung',
    'Tap a day to see its recovery.': 'Tippe einen Tag an, um seine Erholung zu sehen.',
    '%@ · recovery %lld': '%@ · Erholung %lld',
    '%@ · no reading': '%@ · keine Messung',
    # FER-225 — Detalle de Recuperación
    'No reading from last night yet — your recent history is below.': 'Noch keine Messung von letzter Nacht – dein bisheriger Verlauf steht unten.',
    "Recovery blends several signals from your nervous system — your HRV above all, plus resting heart rate, sleep and breathing — and compares them with your own baseline from recent weeks. It's an estimate of how ready your body is today, not a diagnosis. (Buchheit 2014)": 'Die Erholung verbindet mehrere Signale deines Nervensystems – vor allem deine HRV, dazu Ruhepuls, Schlaf und Atmung – und vergleicht sie mit deiner eigenen Basislinie der letzten Wochen. Es ist eine Schätzung, wie bereit dein Körper heute ist, keine Diagnose. (Buchheit 2014)',
    'Information about recovery': 'Informationen zur Erholung',
    'Above your baseline — your body is ready for a strong day.': 'Über deiner Basislinie – dein Körper ist bereit für einen starken Tag.',
    'Recovering — train, but keep it controlled.': 'In Erholung – trainiere, aber kontrolliert.',
    'Low — prioritize rest today.': 'Niedrig – heute Erholung priorisieren.',
    'Calibrating — we need a few more nights of your strap.': 'Kalibrierung – wir brauchen noch ein paar Nächte mit deinem Band.',
    'No recovery yet. Wear your strap overnight and open this again after it syncs — or import your WHOOP history in Data Sources.': 'Noch keine Erholung. Trag dein Band über Nacht und öffne dies erneut, sobald es synchronisiert – oder importiere deinen WHOOP-Verlauf unter Datenquellen.',
    'What explains your recovery': 'Was deine Erholung erklärt',
    "HRV carries the most weight — it's the best window onto your autonomic nervous system. What matters is the average of your recent nights, not a single day. If a signal is missing on a given night, its weight is shared among the others. (Plews 2013; Buchheit 2014)": 'Die HRV hat das größte Gewicht – sie ist das beste Fenster zu deinem autonomen Nervensystem. Es zählt der Durchschnitt deiner letzten Nächte, nicht ein einzelner Tag. Fehlt in einer Nacht ein Signal, wird sein Gewicht auf die anderen verteilt. (Plews 2013; Buchheit 2014)',
    'Information about what explains your recovery': 'Informationen dazu, was deine Erholung erklärt',
    'above your base': 'über deiner Basis',
    'a touch low': 'etwas niedrig',
    'suppressed': 'unterdrückt',
    'low, in your base': 'niedrig, in deiner Basis',
    'running high': 'etwas erhöht',
    'elevated': 'erhöht',
    'solid': 'solide',
    'light': 'leicht',
    'very short': 'sehr kurz',
    'running warm': 'etwas warm',
    'slightly raised': 'leicht erhöht',
    'Your personal baseline: the average of your recent recovery days ± a band of your own variation. A day outside the band is unusual for you, not for the population. (Buchheit 2014)': 'Deine persönliche Basislinie: der Durchschnitt deiner letzten Erholungstage ± ein Band deiner eigenen Schwankung. Ein Tag außerhalb des Bands ist für dich ungewöhnlich, nicht für die Allgemeinheit. (Buchheit 2014)',
    '%lld–%lld · %lld days': '%lld–%lld · %lld Tage',
    "Where your recovery usually lands when you're well. Worth noting when a day falls outside it.": 'Wo deine Erholung normalerweise liegt, wenn es dir gut geht. Achte darauf, wenn ein Tag herausfällt.',
    "The line is your 7-day moving average over the period you pick. The percentage compares this month's average with last month's. Average, Median, Lowest, Highest and σ (how spread out your days are) come from the range you selected.": 'Die Linie ist dein gleitender 7-Tage-Durchschnitt im gewählten Zeitraum. Der Prozentwert vergleicht den Durchschnitt dieses Monats mit dem des Vormonats. Durchschnitt, Median, Minimum, Maximum und σ (wie stark deine Tage streuen) stammen aus dem gewählten Bereich.',
    '+%lld% vs last month': '+%lld% ggü. Vormonat',
    '−%lld% vs last month': '−%lld% ggü. Vormonat',
    'Not enough days in this range to draw a trend.': 'Nicht genügend Tage in diesem Bereich für einen Trend.',
    'Coefficient of variation = how spread out your recovery is around its own average, as a percentage. Low = steady. A steadier recovery usually means your body is coping well with your load. (Plews 2013)': 'Variationskoeffizient = wie stark deine Erholung um ihren eigenen Durchschnitt streut, in Prozent. Niedrig = stabil. Eine stabilere Erholung bedeutet meist, dass dein Körper deine Belastung gut verkraftet. (Plews 2013)',
    '±%lld% week to week · %@': '±%lld% von Woche zu Woche · %@',
    'How steady your recovery stays from one week to the next.': 'Wie stabil deine Erholung von einer Woche zur nächsten bleibt.',
    'Calendar · 90 days': 'Kalender · 90 Tage',
    "Each square is a day, tinted by your recovery — red when low, amber in the middle, green when high. Empty squares are days with no reading. It's the at-a-glance shape of your last three months. (Buchheit 2014)": 'Jedes Kästchen ist ein Tag, eingefärbt nach deiner Erholung – rot bei niedrig, bernstein in der Mitte, grün bei hoch. Leere Kästchen sind Tage ohne Messung. So siehst du auf einen Blick die Form deiner letzten drei Monate. (Buchheit 2014)',
    'Information about the 90-day calendar': 'Informationen zum 90-Tage-Kalender',
    'Each square is a day, tinted by your recovery; empty squares are days with no reading.': 'Jedes Kästchen ist ein Tag, eingefärbt nach deiner Erholung; leere Kästchen sind Tage ohne Messung.',
    'Recent load': 'Aktuelle Belastung',
    "The acute:chronic workload ratio (your last week vs your last month) and training monotony describe how your load is trending. They are context for your recovery — they do NOT predict injuries; that evidence doesn't hold up. (Impellizzeri 2020)": 'Das Verhältnis von akuter zu chronischer Belastung (deine letzte Woche vs. dein letzter Monat) und die Trainingsmonotonie beschreiben, wie sich deine Belastung entwickelt. Sie sind Kontext für deine Erholung – sie sagen KEINE Verletzungen voraus; diese Evidenz hält nicht stand. (Impellizzeri 2020)',
    'Information about recent load': 'Informationen zur aktuellen Belastung',
    'Similar effort most days — a little variety helps.': 'Ähnliche Anstrengung an den meisten Tagen – etwas Abwechslung hilft.',
    'context, not injury risk': 'Kontext, kein Verletzungsrisiko',
    "Each signal becomes a score of how far above or below your personal average it sits (a z-score). They're combined with the weights above and mapped onto a 0–100 scale through a logistic curve, calibrated so a typical day lands near 58. It's an estimate, not a diagnosis.": 'Jedes Signal wird zu einem Wert dafür, wie weit über oder unter deinem persönlichen Durchschnitt es liegt (ein z-Wert). Sie werden mit den obigen Gewichten kombiniert und über eine logistische Kurve auf eine Skala von 0–100 abgebildet, kalibriert so, dass ein typischer Tag nahe 58 liegt. Es ist eine Schätzung, keine Diagnose.',
    '%lld / %lld nights': '%lld / %lld Nächte',
    "We need a few more nights with your strap to learn your baseline before we score your recovery. We'd rather not show a made-up number.": 'Wir brauchen noch ein paar Nächte mit deinem Band, um deine Basislinie zu lernen, bevor wir deine Erholung berechnen. Wir zeigen lieber keine erfundene Zahl.',
    # Detalle de Sueño — pasada de UI: etapas + métricas con tarjeta + copy (FER-227).
    "Each point is one night. The recommended zone for an adult is 7–9 h.": "Jeder Punkt ist eine Nacht. Der empfohlene Bereich für Erwachsene liegt bei 7–9 h.",
    "Weekly debt": "Wochenschuld",
    "What you missed versus what your body needs. One good night won't clear it.": "Was dir gegenüber dem Bedarf deines Körpers gefehlt hat. Eine gute Nacht gleicht das nicht aus.",
    # Detalle de Sueño — tendencia unificada con Hoy + gráfica de deuda (FER-249 v2).
    "behind this week": "im Rückstand diese Woche",
    "your need": "dein Bedarf",
    "%lld of the last %lld nights in this range": "%1$lld der letzten %2$lld Nächte in diesem Bereich",
    "Hours above or below your sleep need, each of the last 7 nights": "Stunden über oder unter deinem Schlafbedarf, in jeder der letzten 7 Nächte",
    "Hours asleep per night, last 14 nights, with classification bands": "Schlafstunden pro Nacht, letzte 14 Nächte, mit Klassifizierungsbändern",
    "slept %@": "geschlafen %@",
    "What the stages mean": "Was die Phasen bedeuten",
    "Shows what this means": "Zeigt, was das bedeutet",
    "Sleep stages": "Schlafphasen",
    "Your night moves through four phases. The watch estimates them from your movement and heart rate, so they're approximate — it gets about 2 of 3 right.": "Deine Nacht durchläuft vier Phasen. Die Uhr schätzt sie aus Bewegung und Herzfrequenz, daher sind sie ungefähr – etwa 2 von 3 stimmen.",
    "Dreams and memory. It consolidates what you learned and processes emotion.": "Träume und Gedächtnis. Festigt Gelerntes und verarbeitet Emotionen.",
    "Physical repair. Your body restores itself and releases growth hormone.": "Körperliche Reparatur. Dein Körper erholt sich und schüttet Wachstumshormon aus.",
    "Most of the night. A transition in which your body winds down.": "Der größte Teil der Nacht. Ein Übergang, in dem dein Körper herunterfährt.",
    "Brief awakenings. They're normal and don't mean a bad night.": "Kurzes Aufwachen. Das ist normal und bedeutet keine schlechte Nacht.",
    "Proportions, not minutes. A clinical measurement needs a sleep study.": "Anteile, keine Minuten. Eine klinische Messung erfordert eine Schlafstudie.",
    "How much you slept versus what your body needs. At 100% you fully covered last night's need.": "Wie viel du im Vergleich zum Bedarf deines Körpers geschlafen hast. Bei 100% hast du den Bedarf der letzten Nacht voll gedeckt.",
    "Your need is your own rolling average of recent nights, never under 7.5 h.": "Dein Bedarf ist dein eigener gleitender Durchschnitt der letzten Nächte, nie unter 7,5 h.",
    "Of the time you spent in bed, how much you actually spent asleep. Above about 85% is considered healthy.": "Von der Zeit im Bett: wie viel du tatsächlich geschlafen hast. Über etwa 85% gilt als gesund.",
    "The share of your sleep spent in deep and REM — the stages that physically and mentally restore you. Around 40–50% is typical for a healthy adult.": "Der Anteil deines Schlafs in Tief- und REM-Schlaf – die Phasen, die dich körperlich und mental erholen. Etwa 40–50% sind bei gesunden Erwachsenen typisch.",
    "How many times you briefly woke during the night. A few are completely normal — everyone surfaces between sleep cycles.": "Wie oft du nachts kurz aufgewacht bist. Ein paar Mal ist völlig normal – jeder taucht zwischen den Schlafzyklen auf.",
    "Brief awakenings are normal and often not remembered. What matters is the trend, not a single night.": "Kurzes Aufwachen ist normal und wird oft nicht erinnert. Wichtig ist der Trend, nicht eine einzelne Nacht.",
    "How long it took you to fall asleep after lights out. Ten to twenty minutes is a healthy range.": "Wie lange du nach dem Lichtausschalten zum Einschlafen gebraucht hast. Zehn bis zwanzig Minuten sind ein gesunder Bereich.",

    # SettingsView — strap-log empty placeholder (FER-199).
    "No activity yet. The log fills in as your strap connects.": "Noch keine Aktivität. Das Protokoll füllt sich, sobald sich dein Strap verbindet.",
    # Cuerpo landing — the «historia / entre-días» tab (FER-186).
    "Rest & load": "Ruhe & Last",
    "Vitals": "Vitalwerte",
    "Longevity": "Langlebigkeit",
    "Ready to train": "Bereit für das Training",
    "Recovering": "In Erholung",
    "Prioritize rest": "Erholung priorisieren",
    "Calibrating your baseline": "Deine Basislinie wird kalibriert",
    "Physical age": "Körperliches Alter",
    "Vitality": "Vitalität",
    "Coming soon": "Demnächst",
    "See all metrics": "Alle Messwerte ansehen",
    "Connect Apple Health to fill steps and more.": "Verbinde Apple Health, um Schritte und mehr zu füllen.",
    # de para llaves de métricas que Cuerpo hace visibles (es ya existía en el catálogo).
    "Respiratory Rate": "Atemfrequenz",
    "Skin Temperature": "Hauttemperatur",
    "No reading yet": "Noch keine Messung",

    # Fitness Age — «Edad física» row in Cuerpo + its detail sheet (FER-141).
    "Estimate": "Schätzung",
    "years": "Jahre",
    "%lld years younger than your %lld": "%lld Jahre jünger als deine %lld",
    "%lld years above your %lld": "%lld Jahre über deinen %lld",
    "Right at your %lld": "Genau bei deinen %lld",
    "Missing resting-HR nights (%lld of 4)": "Fehlende Ruhe-HF-Nächte (%lld von 4)",
    "%lld years younger than your age of %lld.": "%lld Jahre jünger als dein Alter von %lld.",
    "%lld years above your age of %lld.": "%lld Jahre über deinem Alter von %lld.",
    "Right at your age of %lld.": "Genau bei deinem Alter von %lld.",
    "An estimate with a ±%lld-year margin.": "Eine Schätzung mit einer Spanne von ±%lld Jahren.",
    "It's a comparison of your fitness, not your biological age or a medical diagnosis.": "Es ist ein Fitnessvergleich, nicht dein biologisches Alter oder eine medizinische Diagnose.",
    "What moves it": "Was es beeinflusst",
    "The lower it is, the younger.": "Je niedriger, desto jünger.",
    "Recent activity": "Aktuelle Aktivität",
    "More active days also bring it down.": "Mehr aktive Tage senken es ebenfalls.",
    "/ 7 days": "/ 7 Tage",
    "What we're using": "Was wir verwenden",
    "Age and sex": "Alter und Geschlecht",
    "%lld, man": "%lld, Mann",
    "%lld, woman": "%lld, Frau",
    "%lld, non-binary": "%lld, nicht-binär",
    "%lld of 7 nights": "%lld von 7 Nächten",
    "%lld of 7 days": "%lld von 7 Tagen",
    "Based on the Nes/HUNT model (2011): it estimates your aerobic capacity from your resting heart rate and activity, and compares it with the average for your age.": "Basierend auf dem Nes/HUNT-Modell (2011): Es schätzt deine aerobe Kapazität aus deiner Ruheherzfrequenz und Aktivität und vergleicht sie mit dem Durchschnitt für dein Alter.",
    "We can't calculate your physical age yet.": "Wir können dein körperliches Alter noch nicht berechnen.",
    "What we need": "Was wir brauchen",
    "%lld of 4 nights needed": "%lld von 4 Nächten nötig",
    "Keep wearing your band overnight and this fills in on its own.": "Trage deine Band weiter über Nacht, dann füllt sich das von selbst.",
    # VO₂max de Apple Salud en el detalle de Edad física (FER-215).
    "Measured by your Apple Watch during exercise.": "Von deiner Apple Watch beim Training gemessen.",
    "The average for your age is around %lld.": "Der Durchschnitt für dein Alter liegt bei etwa %lld.",
    "Connect Apple Health to see your VO₂max.": "Verbinde Apple Health, um deinen VO₂max zu sehen.",

    # WhyVerdictSheet — de copy: level names (es existed) + red color name (FER-167).
    "Primed": "Bereit",
    "Balanced": "Ausgeglichen",
    "Strained": "Beansprucht",
    "Run down": "Erschöpft",
    "red": "rot",

    # MetricInfoSheet — light-theme redesign + de copy (FER-162).
    # Headlines.
    "Cardiovascular load scored 0–21. Each second of the day your heart rate is recorded, it's assigned to a zone (1–5). Higher zones carry more weight. The total is compressed logarithmically so 21 represents a theoretical maximum — a full day at peak intensity.": "Die kardiovaskuläre Belastung auf einer Skala von 0 bis 21. Jede Sekunde, in der deine Herzfrequenz erfasst wird, fällt in eine Zone (1 bis 5); höhere Zonen zählen mehr. Die Summe wird logarithmisch verdichtet, sodass 21 ein theoretisches Maximum ist: ein ganzer Tag bei höchster Intensität.",
    "Total time asleep last night, estimated from movement and heart rate. Sleep contributes ~15% of your recovery score and feeds the strain-to-load balance (ACWR).": "Die gesamte Schlafzeit der letzten Nacht, geschätzt aus Bewegung und Herzfrequenz. Schlaf macht etwa 15% deiner Erholung aus und fließt in das Verhältnis von Belastung zu Last (ACWR) ein.",
    "Your heart rate when your body is fully at rest — how hard your heart has to work doing nothing. Lower generally means a stronger, more efficient cardiovascular system. Cénit uses it as ~20% of your recovery score; a rise from your norm can signal fatigue or that something's coming on.": "Deine Herzfrequenz, wenn dein Körper vollständig ruht — wie viel dein Herz im Nichtstun leisten muss. Niedriger bedeutet meist ein stärkeres, effizienteres Herz-Kreislauf-System. Cénit nutzt sie als etwa 20% deiner Erholung; ein Anstieg gegenüber deiner Norm kann auf Müdigkeit oder etwas Aufziehendes hindeuten.",
    "Percentage of haemoglobin carrying oxygen in your blood. Healthy adults typically stay above 95%. A drop can indicate altitude effects, sleep apnea, or respiratory illness.": "Der Anteil deines Hämoglobins, der Sauerstoff transportiert. Bei gesunden Erwachsenen liegt er meist über 95%. Ein Abfall kann auf Höhe, Schlafapnoe oder eine Atemwegserkrankung hindeuten.",
    "Daily step count. Consistent activity — even a 30-minute walk — supports cardiovascular health, mood, and recovery quality.": "Deine Schrittzahl des Tages. Beständige Aktivität — schon ein 30-minütiger Spaziergang — unterstützt Herz-Kreislauf-Gesundheit, Stimmung und Erholungsqualität.",
    "Your heart rate across the day, averaged in 5-minute buckets.": "Deine Herzfrequenz über den Tag, gemittelt in 5-Minuten-Intervallen.",
    # Notes.
    "Measured overnight from your strap; when the strap isn't worn, Cénit uses Apple Health's resting heart rate instead.": "Wird nachts mit deinem Strap gemessen; wenn du ihn nicht trägst, nutzt Cénit die Ruhe-Herzfrequenz aus Apple Health.",
    "Wrist-based sensors have lower accuracy than medical pulse oximeters — treat values as a trend, not a clinical reading.": "Sensoren am Handgelenk sind ungenauer als medizinische Pulsoximeter — sieh die Werte als Trend, nicht als klinische Messung.",
    "Steps come from Apple Health and are not recorded by the WHOOP strap.": "Schritte stammen aus Apple Health und werden vom WHOOP-Strap nicht erfasst.",
    # Zone labels.
    "Rest / Light": "Ruhe / leicht",
    "Moderate": "Moderat",
    "Hard": "Hart",
    "Extreme": "Extrem",
    "Short": "Kurz",
    "Adequate": "Ausreichend",
    "Optimal": "Optimal",
    "Extended": "Lang",
    "Athlete": "Athlet",
    "Excellent": "Ausgezeichnet",
    "Normal": "Normal",
    "Elevated": "Erhöht",
    "Borderline": "Grenzwertig",
    "Sedentary": "Sitzend",
    "Active": "Aktiv",
    "Very active": "Sehr aktiv",
    # Section titles / wells / connect hint.
    "Last 14 days": "Letzte 14 Tage",
    "No data for the last 14 days.": "Keine Daten der letzten 14 Tage.",
    "This reading can come from Apple Health. Connect it from Today to see it here.": "Dieser Wert kann aus Apple Health stammen. Verbinde ihn über Heute, um ihn hier zu sehen.",
    "%lld of %lld nights": "%lld von %lld Nächten",
    "Beats per minute": "Schläge pro Minute",
    "5-minute average · since midnight": "5-Minuten-Mittel · seit Mitternacht",
    "Calibrating baseline": "Basislinie wird kalibriert",
    "Skin temp": "Hauttemp.",
    "Respiration": "Atmung",
    "See the method": "Methode ansehen",
    # HRV / Recovery explainer copy (es existed; de added here).
    "HRV is how much the time between your heartbeats varies, in milliseconds, while you sleep. More variation usually means better recovery. What matters isn't the number itself, but how it compares with your own average.": "Die HRV ist, wie stark die Zeit zwischen deinen Herzschlägen im Schlaf schwankt, in Millisekunden. Mehr Schwankung bedeutet meist bessere Erholung. Wichtig ist nicht die Zahl selbst, sondern wie sie sich mit deinem eigenen Durchschnitt vergleicht.",
    "HRV is personal. There are no universal good/bad thresholds — only your trend over time.": "Die HRV ist persönlich. Es gibt keine allgemeingültigen Gut-/Schlecht-Schwellen — nur deinen Trend über die Zeit.",
    "No HRV from last night. That can happen if you didn't wear the strap, or the night was too short to gather 20 clean beats.": "Keine HRV aus der letzten Nacht. Das kann passieren, wenn du den Strap nicht getragen hast oder die Nacht zu kurz war, um 20 saubere Schläge zu sammeln.",
    "We take the intervals between your heartbeats overnight, drop any outside 300–2000 ms and any that deviate more than 20% from their neighbours (ectopic beats). If at least 20 clean beats remain, we compute RMSSD.": "Wir nehmen die Intervalle zwischen deinen Herzschlägen über Nacht, verwerfen alle außerhalb von 300–2000 ms sowie solche, die mehr als 20% von ihren Nachbarn abweichen (ektope Schläge). Bleiben mindestens 20 saubere Schläge übrig, berechnen wir den RMSSD.",
    "RMSSD (Task Force, 1996); ectopic rejection by Malik's rule. HRV is about 60% of your recovery score.": "RMSSD (Task Force, 1996); Ausschluss ektoper Schläge nach Maliks Regel. Die HRV macht etwa 60% deiner Erholung aus.",
    "Your recovery sums up how ready your body is today, from 0 to 100. It blends several signals from your night — your HRV above all — and compares them with your own average from recent weeks, not anyone else's.": "Deine Erholung fasst zusammen, wie bereit dein Körper heute ist, von 0 bis 100. Sie verbindet mehrere Signale deiner Nacht — vor allem deine HRV — und vergleicht sie mit deinem eigenen Durchschnitt der letzten Wochen, nicht mit dem anderer.",
    "If a signal is missing on a given night, its weight is shared among the others.": "Fehlt ein Signal in einer Nacht, wird sein Gewicht auf die anderen verteilt.",
    "It's an estimate, not a diagnosis.": "Es ist eine Schätzung, keine Diagnose.",
    "Each signal becomes a score of how far above or below your personal average it sits; they're averaged with the weights above and mapped onto a 0–100 scale, calibrated so a typical day lands near 58.": "Jedes Signal wird zu einem Wert, wie weit es über oder unter deinem persönlichen Durchschnitt liegt; sie werden mit den obigen Gewichten gemittelt und auf eine Skala von 0–100 abgebildet, kalibriert so, dass ein typischer Tag nahe 58 landet.",
    "A composite of z-scores through a logistic curve. HRV via RMSSD (Task Force, 1996).": "Ein Verbund aus z-Werten durch eine logistische Kurve. HRV über RMSSD (Task Force, 1996).",
    "We can't score your recovery yet. We need at least %lld nights with your strap to learn your baseline; you're at %lld of %lld. We'd rather not show you a made-up number.": "Wir können deine Erholung noch nicht berechnen. Wir brauchen mindestens %lld Nächte mit deinem Strap, um deine Basislinie zu lernen; du bist bei %lld von %lld. Wir zeigen dir lieber keine erfundene Zahl.",

    # Symbols / pure placeholders — identical in German.
    "—": "—",
    "·": "·",
    "· %@": "· %@",
    "/ %lld": "/ %lld",
    "%@": "%@",
    "%@ – %@": "%@ – %@",
    "%@ · %@": "%@ · %@",
    "%@ · n = %lld": "%@ · n = %lld",
    "%@ / %@": "%@ / %@",
    "%@ %@": "%@ %@",
    "%@ ↔ %@": "%@ ↔ %@",
    "%@, %@%@": "%@, %@%@",
    "%@%@": "%@%@",
    "%lld": "%lld",
    "%lld / %lld": "%lld / %lld",
    "•": "•",
    "✓": "✓",
    "r = %@": "r = %@",
    "v%@": "v%@",
    "NOOP": "NOOP",
    "NOOP %@": "NOOP %@",

    # Units / short tokens.
    "% Max": "% Max",
    "bpm": "bpm",
    "BPM": "BPM",
    "Δ vs prev": "Δ vs. vorher",

    # Format strings.
    "%@ versus %@, r equals %@, %lld days": "%@ gegen %@, r gleich %@, %lld Tage",
    "%@ wrist alerts": "%@ Handgelenk-Hinweise",
    "%@, correlation %@, %lld days": "%@, Korrelation %@, %lld Tage",
    "%@, range %@ to %@": "%@, Bereich %@ bis %@",
    "%@: %@ last night%@": "%@: %@ letzte Nacht%@",
    "%lld app%@ on": "%lld App%@ aktiv",
    "%lld breaths": "%lld Atemzüge",
    "%lld days · %lld sleeps stored": "%lld Tage · %lld Schlafphasen gespeichert",
    "%lld frame%@ captured this session.": "%lld Frame%@ in dieser Sitzung erfasst.",
    "%lld of %lld nights": "%lld von %lld Nächten",
    "%lld overlapping days · %@ %@ correlation": "%lld überlappende Tage · %@ %@ Korrelation",
    "%lld–%lld%@ · step %lld": "%lld–%lld%@ · Schritt %lld",
    "%@ is free and always will be. If it's useful to you, you can chip in to help with development and testing costs. Totally optional.": "%@ ist kostenlos und bleibt es. Wenn es dir nützt, kannst du etwas zu den Entwicklungs- und Testkosten beitragen. Völlig freiwillig.",
    "Age, %lld years": "Alter, %lld Jahre",
    "Auto · %lld bpm (Tanaka)": "Automatisch · %lld bpm (Tanaka)",
    "Battery %lld%%": "Akku %lld%%",
    "Battery %lld%% · Charging": "Akku %lld%% · Lädt",
    "Choose the buzz pattern for %@": "Vibrationsmuster für %@ wählen",
    "Coach said: %@": "Coach sagte: %@",
    "Copy %@ address": "%@-Adresse kopieren",
    "Email %@": "E-Mail %@",
    "Error: %@": "Fehler: %@",
    "Estimated max heart rate · %lld bpm": "Geschätzte maximale Herzfrequenz · %lld bpm",
    "Fetch the available models from %@ using your saved key": "Verfügbare Modelle von %@ mit deinem gespeicherten Schlüssel abrufen",
    "Heart rate %lld beats per minute": "Herzfrequenz %lld Schläge pro Minute",
    "Max heart rate override, %@": "Manuelle maximale Herzfrequenz, %@",
    "Mean %@": "Mittelwert %@",
    "No data for these metrics in %@. Widen the range or pick metrics you've logged.": "Keine Daten für diese Metriken in %@. Erweitere den Bereich oder wähle Metriken, die du erfasst hast.",
    "Not enough overlapping days between these metrics in %@. Widen the range.": "Nicht genug überlappende Tage zwischen diesen Metriken in %@. Erweitere den Bereich.",
    "Nothing in the catalog moves clearly with %@ over this window. Widen the range to surface relationships.": "Nichts im Katalog bewegt sich in diesem Zeitraum klar mit %@. Erweitere den Bereich, um Zusammenhänge sichtbar zu machen.",
    "of 3 · %@": "von 3 · %@",
    "Paste your %@ API key": "Füge deinen %@-API-Schlüssel ein",
    "Pearson r · %@": "Pearson r · %@",
    "Questions, feedback, bugs — %@": "Fragen, Feedback, Fehler — %@",
    "Reading your %@…": "%@ wird gelesen…",
    "Remove %@": "%@ entfernen",
    "Scan with any %@ wallet": "Mit einer beliebigen %@-Wallet scannen",
    "Show %@ donation address": "%@-Spendenadresse anzeigen",
    "Sleep stage breakdown: deep %lld percent, light %lld percent, REM %lld percent, awake %lld percent": "Schlafphasen-Aufschlüsselung: Tief %lld Prozent, Leicht %lld Prozent, REM %lld Prozent, Wach %lld Prozent",
    "Stress · %@": "Stress · %@",
    "Stress %@ of 3, %@": "Stress %@ von 3, %@",
    "Suggested prompt: %@": "Vorgeschlagene Frage: %@",
    "Test %@ buzz": "%@-Testvibration",
    "This is the only feature that leaves your Mac — it sends a summary of your metrics to %@ using your own key. Nothing is sent until you ask.": "Dies ist die einzige Funktion, die deinen Mac verlässt — sie sendet eine Zusammenfassung deiner Metriken mit deinem eigenen Schlüssel an %@. Es wird nichts gesendet, bis du es anforderst.",
    "What moves your %@": "Was deine %@ beeinflusst",
    "You said: %@": "Du sagtest: %@",

    # Sentences / labels.
    "A private window into your recovery, sleep and strain — read straight from your strap, kept only on this Mac.": "Ein privater Blick auf deine Erholung, deinen Schlaf und deine Belastung — direkt vom Strap gelesen und nur auf diesem Mac gespeichert.",
    "A standalone companion for your WHOOP. Everything stays on this device — your history, your live stream, your numbers. Nothing is uploaded. NOOP is an independent, experimental project, not the WHOOP app.": "Ein eigenständiger Begleiter für dein WHOOP. Alles bleibt auf diesem Gerät — deine Historie, dein Live-Stream, deine Werte. Nichts wird hochgeladen. NOOP ist ein unabhängiges, experimentelles Projekt, nicht die WHOOP-App.",
    "About": "Über",
    "Active energy": "Aktive Energie",
    "Activity": "Aktivität",
    "Activity & Energy": "Aktivität & Energie",
    "Activity Breakdown": "Aktivitätsaufschlüsselung",
    "Acute (7-day) vs chronic (28-day) training load. 0.8–1.3 is the sweet spot.": "Akute (7 Tage) vs. chronische (28 Tage) Trainingslast. 0,8–1,3 ist der ideale Bereich.",
    # Short load-band words for the verdict hero (LoadBand.shortLabel) + its VoiceOver label.
    "Light load": "Leichte Last",
    "Ideal load": "Ideale Last",
    "Rising load": "Steigende Last",
    "High load": "Hohe Last",
    "Training load: %@ (acute:chronic %@)": "Trainingslast: %@ (akut:chronisch %@)",
    "Add a metric to compare": "Eine Metrik zum Vergleich hinzufügen",
    "Add metric": "Metrik hinzufügen",
    "Age": "Alter",
    "All Sessions": "Alle Sitzungen",
    "ALL YOUR DATA · NONE OF THE CLOUD": "ALL DEINE DATEN · NICHTS IN DER CLOUD",
    "all your data, none of the cloud": "all deine Daten, nichts in der Cloud",
    "Any amount helps. Thank you — genuinely.": "Jeder Betrag hilft. Danke — wirklich.",
    "API key": "API-Schlüssel",
    "Apple": "Apple",
    "Apple Health": "Apple Health",
    "Ask about your recovery, strain, sleep and workouts — grounded in your own numbers.": "Frage nach deiner Erholung, Belastung, deinem Schlaf und deinen Workouts — basierend auf deinen eigenen Werten.",
    "Ask Coach about your data…": "Frage den Coach zu deinen Daten…",
    "Ask your first question": "Stelle deine erste Frage",
    "Asleep": "Schlafend",
    "Asleep avg": "Schlaf Ø",
    "Asleep duration": "Schlafdauer",
    "At a glance": "Auf einen Blick",
    "Auto": "Automatisch",
    "Automations": "Automationen",
    "Autonomic load from HRV and resting heart rate": "Autonome Last aus HRV und Ruheherzfrequenz",
    "Average": "Durchschnitt",
    "Avg": "Ø",
    "Awake": "Wach",
    "Back": "Zurück",
    "Backup & restore": "Sicherung & Wiederherstellung",
    "Behaviour Effects": "Verhaltenseffekte",
    "Blood oxygen": "Blutsauerstoff",
    "Blood Oxygen": "Blutsauerstoff",
    "BMI": "BMI",
    "Body Composition": "Körperzusammensetzung",
    "Body fat": "Körperfett",
    "Body Fat": "Körperfett",
    "Bond your strap on the Live screen to feel the transitions hands-free.": "Verbinde deinen Strap im Live-Bildschirm, um die Übergänge freihändig zu spüren.",
    "Breathe": "Atmen",
    "Building from your strap": "Wird von deinem Strap aufgebaut",
    "Built on": "Basiert auf",
    "Buzz cues on": "Vibrationshinweise an",
    "Buzz strap": "Strap vibrieren",
    "Buzz your strap when these apps notify you. Everything runs on this Mac.": "Lass deinen Strap vibrieren, wenn diese Apps dich benachrichtigen. Alles läuft auf diesem Mac.",
    "Buzzes your wrist": "Vibriert an deinem Handgelenk",
    "By sport": "Nach Sportart",
    "Calendar": "Kalender",
    "Calibrating": "Kalibrierung",
    "Calm time": "Ruhezeit",
    "Calories": "Kalorien",
    "Cardiac": "Herz",
    "Category": "Kategorie",
    "Choose export…": "Export wählen…",
    "Choose export.zip…": "export.zip wählen…",
    "Clear": "Löschen",
    "Close": "Schließen",
    "Close Support": "Support schließen",
    "Coach": "Coach",
    "Coach is thinking": "Coach denkt nach",
    "Coach is thinking…": "Coach denkt nach…",
    "Coach reads a summary of your last two weeks plus 30-day averages and recent workouts, then answers in plain language. Try a suggestion below.": "Der Coach liest eine Zusammenfassung deiner letzten zwei Wochen sowie 30-Tage-Durchschnitte und aktuelle Workouts und antwortet dann in klarer Sprache. Probiere einen Vorschlag unten aus.",
    "Coach uses your own API key. Pick a provider, paste a key, and choose a model. Your key is stored securely in the macOS Keychain and never leaves your Mac except as the request you make.": "Der Coach nutzt deinen eigenen API-Schlüssel. Wähle einen Anbieter, füge einen Schlüssel ein und wähle ein Modell. Dein Schlüssel wird sicher im macOS-Schlüsselbund gespeichert und verlässt deinen Mac nur als die Anfrage, die du stellst.",
    "Coherence estimate": "Kohärenz-Schätzung",
    "Coming together": "Wird zusammengeführt",
    "Compare": "Vergleichen",
    "Compare needs at least two metrics with history. Import your WHOOP export in Data Sources first.": "Für den Vergleich werden mindestens zwei Metriken mit Verlauf benötigt. Importiere zuerst deinen WHOOP-Export unter Datenquellen.",
    "Complete": "Abgeschlossen",
    "Configure": "Konfigurieren",
    "Connect a provider": "Anbieter verbinden",
    "Connect strap for buzz cues": "Strap für Vibrationshinweise verbinden",
    "Connect your strap for haptic guidance — you'll feel one pulse on the inhale, two on the exhale, so you can breathe with your eyes closed.": "Verbinde deinen Strap für haptische Führung — du spürst einen Impuls beim Einatmen, zwei beim Ausatmen, sodass du mit geschlossenen Augen atmen kannst.",
    "Connect your strap to enable": "Verbinde deinen Strap zum Aktivieren",
    "Connect your strap to test": "Verbinde deinen Strap zum Testen",
    "Connected": "Verbunden",
    "Connecting…": "Verbinde…",
    "Consistency": "Konsistenz",
    "Control Center": "Kontrollzentrum",
    "Copied!": "Kopiert!",
    "Copy": "Kopieren",
    "Copy address": "Adresse kopieren",
    "Crunching your raw streams…": "Deine Rohdaten werden verarbeitet…",
    "Custom model id": "Eigene Modell-ID",
    "Custom…": "Benutzerdefiniert…",
    "Daily signals": "Tägliche Signale",
    "Data Sources": "Datenquellen",
    "Date": "Datum",
    "Day strain": "Tagesbelastung",
    "Day Strain": "Tagesbelastung",
    "Days": "Tage",
    "Deep": "Tief",
    "Depleted": "Erschöpft",
    "Disconnect": "Trennen",
    "Don't see it? That's normal.": "Nicht zu sehen? Das ist normal.",
    "Donation QR code": "Spenden-QR-Code",
    "Effect size": "Effektstärke",
    "Efficiency": "Effizienz",
    "Email": "E-Mail",
    "Enable wrist alerts": "Handgelenk-Hinweise aktivieren",
    "Enter a model id": "Modell-ID eingeben",
    "Estimate only — a higher RMSSD while paced usually means your parasympathetic \"rest\" branch is engaging. It is not a clinical reading; trends over a session matter more than any single number.": "Nur eine Schätzung — ein höherer RMSSD beim getakteten Atmen bedeutet meist, dass dein parasympathischer \"Ruhe\"-Zweig aktiv wird. Es ist kein klinischer Wert; Trends über eine Sitzung sind wichtiger als ein einzelner Wert.",
    "Every beat, every night, every day — woven into one quiet picture of you. Welcome to NOOP.": "Jeder Schlag, jede Nacht, jeder Tag — verwoben zu einem ruhigen Bild von dir. Willkommen bei NOOP.",
    "Every session, threaded together.": "Jede Sitzung, miteinander verwoben.",
    "Every signal, one tap deep.": "Jedes Signal, nur einen Tipp entfernt.",
    "Everything stays on this Mac. Bring your history in once, then it's yours.": "Alles bleibt auf diesem Mac. Importiere deine Historie einmal, dann gehört sie dir.",
    "Experimental · WHOOP 5 / MG": "Experimentell · WHOOP 5 / MG",
    "EXPLORATORY": "EXPLORATIV",
    "Explore": "Entdecken",
    "Export frames…": "Frames exportieren…",
    "Export…": "Exportieren…",
    "Female": "Weiblich",
    "Find it in the sidebar under Data Sources.": "Du findest es in der Seitenleiste unter Datenquellen.",
    "Fire a single haptic pulse on the strap (requires a bonded connection)": "Einen einzelnen haptischen Impuls am Strap auslösen (erfordert eine gekoppelte Verbindung)",
    "Fire a test buzz now": "Jetzt eine Testvibration auslösen",
    "Fire a test haptic buzz on the strap (requires an active strap connection)": "Eine haptische Testvibration am Strap auslösen (erfordert eine aktive Strap-Verbindung)",
    "Fires a test buzz on your strap": "Löst eine Testvibration an deinem Strap aus",
    "Forget the saved key and disconnect": "Gespeicherten Schlüssel vergessen und trennen",
    "From": "Von",
    "Get in touch": "Kontakt aufnehmen",
    "Get the latest release": "Neueste Version laden",
    "Got it": "Verstanden",
    "Haptic-paced breathing · watch your HRV respond": "Haptisch getaktetes Atmen · beobachte, wie deine HRV reagiert",
    "Haptics on": "Haptik an",
    "Health": "Gesundheit",
    "Health Monitor": "Gesundheitsmonitor",
    "Heart & Vitals": "Herz & Vitalwerte",
    "Heart Rate": "Herzfrequenz",
    "HEART RATE": "HERZFREQUENZ",
    "Heart rate variability": "Herzfrequenzvariabilität",
    "Height": "Größe",
    "high": "hoch",
    "History": "Verlauf",
    "History synced %@": "Verlauf synchronisiert %@",
    "Hours asleep": "Schlafstunden",
    "Hours vs Needed": "Stunden vs. Bedarf",
    "How They Move Together": "Wie sie sich gemeinsam bewegen",
    "How this is computed": "Wie das berechnet wird",
    "How this works": "Wie das funktioniert",
    "HR Zones": "HF-Zonen",
    "HRV": "HRV",
    "I keep this project anonymous, so crypto is the only way to chip in — no Patreon, no PayPal, no name attached. Quick, global, and private for both of us.": "Ich halte dieses Projekt anonym, daher ist Krypto die einzige Möglichkeit, beizutragen — kein Patreon, kein PayPal, kein Name. Schnell, weltweit und privat für uns beide.",
    "Import your history first. A WHOOP export in Data Sources fills every metric you can explore here in about a minute.": "Importiere zuerst deine Historie. Ein WHOOP-Export unter Datenquellen füllt in etwa einer Minute jede Metrik, die du hier erkunden kannst.",
    "Import…": "Importieren…",
    "Importing overwrites everything currently on this Mac. Your old data is kept in a side file just in case. NOOP needs a relaunch for an import to take effect.": "Der Import überschreibt alles, was sich derzeit auf diesem Mac befindet. Deine alten Daten werden sicherheitshalber in einer separaten Datei aufbewahrt. NOOP muss neu gestartet werden, damit ein Import wirksam wird.",
    "Importing…": "Importiere…",
    "Insights": "Einblicke",
    "Insights read your journal and outcomes. Import your WHOOP export, which includes your journal, in Data Sources to unlock them.": "Einblicke lesen dein Journal und deine Ergebnisse. Importiere deinen WHOOP-Export, der dein Journal enthält, unter Datenquellen, um sie freizuschalten.",
    "Intelligence": "Intelligenz",
    "Interrogate what affects what.": "Untersuche, was was beeinflusst.",
    "Interval Timer": "Intervall-Timer",
    "Intervals": "Intervalle",
    "Key Metrics": "Kernmetriken",
    "Last night": "Letzte Nacht",
    "Last night, read in two seconds.": "Letzte Nacht, in zwei Sekunden erfasst.",
    "Last Workouts": "Letzte Workouts",
    "Latest": "Aktuellste",
    "Latest reading": "Aktuellster Messwert",
    "Lean body mass": "Magermasse",
    "Lean Mass": "Magermasse",
    "Learning your baseline — %lld of %lld nights.": "Deine Baseline wird gelernt — %lld von %lld Nächten.",
    "Let the coach use my data": "Dem Coach erlauben, meine Daten zu nutzen",
    "Light": "Leicht",
    "Live": "Live",
    "Live heart rate already works on a WHOOP 5/MG strap. These probes go further and try to coax more out of it. They are guesses, off by default, and only ever touch a 5/MG strap — WHOOP 4.0 is never affected.": "Die Live-Herzfrequenz funktioniert bereits an einem WHOOP 5/MG-Strap. Diese Tests gehen weiter und versuchen, mehr herauszuholen. Es sind Vermutungen, standardmäßig deaktiviert, und betreffen nur einen 5/MG-Strap — WHOOP 4.0 ist nie betroffen.",
    "Live now. Your scores are building.": "Jetzt live. Deine Werte werden aufgebaut.",
    "Live vitals, streamed from the strap.": "Live-Vitalwerte, gestreamt vom Strap.",
    "load %@": "Last %@",
    "Loading your history…": "Deine Historie wird geladen…",
    "Loading your sessions…": "Deine Sitzungen werden geladen…",
    "Loading your sleep history…": "Dein Schlafverlauf wird geladen…",
    "Log": "Protokoll",
    "low": "niedrig",
    "Low": "Niedrig",
    "Make the strap do things — tap to act, walk away to lock, train by feel.": "Lass den Strap Dinge tun — tippen zum Auslösen, weggehen zum Sperren, nach Gefühl trainieren.",
    "Male": "Männlich",
    "Manual override": "Manuelle Übersteuerung",
    "Markers": "Marker",
    "Max": "Max",
    "Max 4": "Max. 4",
    "Max heart rate": "Maximale Herzfrequenz",
    "Max heart rate override": "Manuelle maximale Herzfrequenz",
    "Max HR": "Max. HF",
    "Metric": "Metrik",
    "Metric Relationships": "Metrik-Beziehungen",
    "Metrics": "Metriken",
    "mid": "mittel",
    "Min": "Min",
    "Model": "Modell",
    "Most Active": "Aktivste",
    "Move all your NOOP data to another machine. Export saves everything — history, sleeps, workouts, settings — to a single file you can copy across; import replaces this Mac's data with a backup.": "Übertrage alle deine NOOP-Daten auf einen anderen Rechner. Der Export speichert alles — Historie, Schlafphasen, Workouts, Einstellungen — in einer einzelnen Datei, die du kopieren kannst; der Import ersetzt die Daten dieses Macs durch eine Sicherung.",
    "Movement": "Bewegung",
    "n.s.": "n.s.",

    # FER-113 — Versöhnung Erholung↔Urteil (Bridge, Sublabel, "Warum?"-Sheet).
    "Several signals are down at once. Treat today as recovery.": "Mehrere Signale sind gleichzeitig unten. Behandle heute als Erholung.",
    "One of your signals is flagging. You can train, but keep it controlled.": "Eines deiner Signale schlägt an. Du kannst trainieren, aber halte es kontrolliert.",
    "You woke up well recovered. What needs care today is your training load, not your body.": "Du bist gut erholt aufgewacht. Worauf du heute achten musst, ist deine Belastung, nicht dein Körper.",
    "Your recovery is high, but %@ is flagging — keep an eye on that today.": "Deine Erholung ist hoch, aber %@ schlägt an — behalte das heute im Auge.",
    "your training load": "deine Belastung",
    "your HRV": "deine HRV",
    "your resting heart rate": "deine Ruheherzfrequenz",
    "your skin temperature": "deine Hauttemperatur",
    "your breathing": "deine Atmung",
    "one of your signals": "eines deiner Signale",
    "several signals": "mehrere Signale",
    "Verdict": "Urteil",
    "from %@": "wegen %@",
    "Why %@?": "Warum %@?",
    "Today your day is %@ — %@": "Heute ist dein Tag %@ — %@",
    "Your signals today": "Deine Signale heute",
    "Opens why today's verdict reads this way": "Öffnet, warum dein heutiges Urteil so ausfällt",
    "What each color means": "Was jede Farbe bedeutet",
    "mint": "Minze",
    "green": "Grün",
    "amber": "Bernstein",
    "rose": "Rosa",
    "gray": "Grau",
    "signals aligned, load supported": "Signale im Einklang, Belastung tragbar",
    "nothing flagging": "nichts schlägt an",
    "one signal needs care": "ein Signal braucht Acht",
    "several signals down": "mehrere Signale unten",
    "TODAY": "HEUTE",

    "Night detail": "Nacht-Details",
    "Nights": "Nächte",
    "No biometrics yet. Import your WHOOP export (and Apple Health if you have it) in Data Sources to fill this in.": "Noch keine Biometrie. Importiere deinen WHOOP-Export (und Apple Health, falls vorhanden) unter Datenquellen, um dies zu füllen.",
    "No data": "Keine Daten",
    "NO DATA": "KEINE DATEN",
    "No nights here yet. Import your WHOOP export — or connect Apple Health — in Data Sources to see your sleep stages and trends. Or open Intelligence to see last night computed from the strap after you wear it to bed.": "Noch keine Nächte hier. Importiere deinen WHOOP-Export — oder verbinde Apple Health — unter Datenquellen, um deine Schlafphasen und Trends zu sehen. Oder öffne Intelligenz, um die letzte Nacht aus dem Strap berechnet zu sehen, nachdem du ihn nachts getragen hast.",
    "No readings recorded.": "Keine Messwerte aufgezeichnet.",
    "No stress history yet. Import your WHOOP export in Data Sources to see it.": "Noch kein Stressverlauf. Importiere deinen WHOOP-Export unter Datenquellen, um ihn zu sehen.",
    "No workouts yet. They come from your WHOOP and Apple Health history. Import in Data Sources to bring them in.": "Noch keine Workouts. Sie stammen aus deinem WHOOP- und Apple-Health-Verlauf. Importiere sie unter Datenquellen.",
    "Non-binary": "Nichtbinär",
    "NOOP — all your data, none of the cloud.": "NOOP — all deine Daten, nichts in der Cloud.",
    "Cénit is free and always will be, nothing is locked. It cost real money and a lot of unpaid hours to build, and there's a Windows app and an iOS app I want to ship next. If it's useful to you and you want to help with the development and testing costs, even a few quid in crypto genuinely keeps it moving, and honestly it keeps me motivated to keep building.": "Cénit ist kostenlos und bleibt es, nichts ist gesperrt. Es hat echtes Geld und viele unbezahlte Stunden gekostet, und es gibt eine Windows-App und eine iOS-App, die ich als Nächstes veröffentlichen möchte. Wenn es dir nützt und du bei den Entwicklungs- und Testkosten helfen möchtest, hält es schon mit ein paar Euro in Krypto wirklich am Laufen — und ehrlich gesagt motiviert es mich, weiterzubauen.",
    "NOOP is not a medical device. It is for informational and personal-insight purposes only and is not intended to diagnose, treat, cure or prevent any condition. Talk to a clinician for medical advice.": "NOOP ist kein medizinisches Gerät. Es dient nur zu Informations- und persönlichen Erkenntniszwecken und ist nicht dazu bestimmt, Erkrankungen zu diagnostizieren, zu behandeln, zu heilen oder zu verhindern. Wende dich für medizinischen Rat an eine Fachperson.",
    "NOOP pairs directly with your WHOOP over Bluetooth — no WHOOP app, no cloud.": "NOOP koppelt sich direkt über Bluetooth mit deinem WHOOP — keine WHOOP-App, keine Cloud.",
    "NOOP scores your recovery, strain and sleep itself — on-device, no cloud.": "NOOP berechnet deine Erholung, Belastung und deinen Schlaf selbst — auf dem Gerät, ohne Cloud.",
    "NOOP-computed": "Von NOOP berechnet",
    "Normalized": "Normalisiert",
    "Normalized overlay": "Normalisierte Überlagerung",
    "Not affiliated with, endorsed by, or connected to WHOOP. Interoperability software for hardware you own and your own data. Use it only with a device you own, and not in breach of any agreement that applies to you. Not a medical device.": "Nicht mit WHOOP verbunden, von WHOOP unterstützt oder zu WHOOP gehörend. Interoperabilitätssoftware für Hardware, die dir gehört, und deine eigenen Daten. Nutze sie nur mit einem Gerät, das dir gehört, und nicht unter Verletzung einer für dich geltenden Vereinbarung. Kein medizinisches Gerät.",
    "Not enough data for this window.": "Nicht genug Daten für diesen Zeitraum.",
    "Not enough nights yet.": "Noch nicht genug Nächte.",
    "Not enough overlapping history to correlate your metrics yet.": "Noch nicht genug überlappender Verlauf, um deine Metriken zu korrelieren.",
    "Not enough recent days to chart a trend yet. Import a history or keep wearing your strap.": "Noch nicht genug aktuelle Tage, um einen Trend darzustellen. Importiere eine Historie oder trage deinen Strap weiter.",
    "Not synced yet": "Noch nicht synchronisiert",
    "Nothing imported yet. On an iPhone: Health app, tap your photo, Export All Health Data, then import the .zip here in Data Sources.": "Noch nichts importiert. Auf einem iPhone: Health-App, tippe auf dein Foto, „Alle Gesundheitsdaten exportieren“, dann importiere die .zip hier unter Datenquellen.",
    "Nothing selected yet.": "Noch nichts ausgewählt.",
    "Notifications": "Mitteilungen",
    "Off": "Aus",
    "Off — the coach answers generally and sends none of your metrics.": "Aus — der Coach antwortet allgemein und sendet keine deiner Metriken.",
    "OK": "OK",
    "On — your recovery, sleep, HRV and workouts are shared with the provider for tailored coaching.": "An — deine Erholung, dein Schlaf, deine HRV und Workouts werden für maßgeschneidertes Coaching mit dem Anbieter geteilt.",
    "On a 5/MG connection NOOP will send a puffin realtime-stream request after the handshake, and log what comes back. If you have a 5/MG strap, turning this on and sharing your strap log helps map the protocol. No effect on WHOOP 4.0.": "Bei einer 5/MG-Verbindung sendet NOOP nach dem Handshake eine Puffin-Echtzeitstream-Anfrage und protokolliert die Antwort. Wenn du einen 5/MG-Strap hast, hilft das Aktivieren und Teilen deines Strap-Protokolls, das Protokoll zu kartieren. Keine Auswirkung auf WHOOP 4.0.",
    "Open-source BLE reverse-engineering work. Thank you.": "Open-Source-BLE-Reverse-Engineering-Arbeit. Danke.",
    "Opens the GitHub releases page in your browser. NOOP itself makes no network connections — the macOS sandbox has no network entitlement.": "Öffnet die GitHub-Releases-Seite in deinem Browser. NOOP selbst stellt keine Netzwerkverbindungen her — die macOS-Sandbox hat keine Netzwerk-Berechtigung.",
    "Outcome metric": "Ergebnismetrik",
    "Overlay": "Überlagerung",
    "Overlay 2–4 signals": "2–4 Signale überlagern",
    "Overlay signals, draw conclusions.": "Signale überlagern, Schlüsse ziehen.",
    "p < 0.05": "p < 0,05",
    "Pause": "Pause",
    "Paused": "Pausiert",
    "Peak": "Spitze",
    "Peaked": "Höchststand",
    "Pearson r": "Pearson r",
    "Pearson r over the visible window · |r| ≥ 0.30, n ≥ 10": "Pearson r über den sichtbaren Bereich · |r| ≥ 0,30, n ≥ 10",
    "Points": "Punkte",
    "Profile": "Profil",
    "Provenance": "Herkunft",
    "Provider": "Anbieter",
    "Question": "Frage",
    "Quiet hours end": "Ende der Ruhezeit",
    "Quiet hours start": "Beginn der Ruhezeit",
    "Re-scan": "Erneut suchen",
    "Readiness": "Bereitschaft",
    "Reading your Apple Health history…": "Dein Apple-Health-Verlauf wird gelesen…",
    "Reading your heart-rate variability and resting heart rate…": "Deine Herzfrequenzvariabilität und Ruheherzfrequenz werden gelesen…",
    "Reading your history…": "Deine Historie wird gelesen…",
    "Reading your journal and outcomes…": "Dein Journal und deine Ergebnisse werden gelesen…",
    "Ready": "Bereit",
    "Ready to scan": "Bereit zum Suchen",
    "Recent moments": "Aktuelle Momente",
    "Recompute": "Neu berechnen",
    "Record puffin frames to a file": "Puffin-Frames in eine Datei aufzeichnen",
    "Recovery": "Erholung",
    "Recovery weighs your HRV against your personal baseline (~60%), resting heart rate (~20%), sleep performance (~15%) and respiration (~5%). Day strain is a 0–21 cardiovascular load from time in heart-rate zones. Sleep is staged from movement and heart rate. Everything is computed here from the strap's raw data — it works for any day NOOP collected raw streams.": "Die Erholung gewichtet deine HRV gegenüber deiner persönlichen Basislinie (~60 %), die Ruheherzfrequenz (~20 %), die Schlafleistung (~15 %) und die Atmung (~5 %). Die Tagesbelastung ist eine kardiovaskuläre Last von 0–21 aus der Zeit in Herzfrequenzzonen. Der Schlaf wird aus Bewegung und Herzfrequenz in Phasen eingeteilt. Alles wird hier aus den Rohdaten des Straps berechnet — es funktioniert für jeden Tag, an dem NOOP Rohdaten erfasst hat.",
    "Refresh models": "Modelle aktualisieren",
    "Refresh models from provider": "Modelle vom Anbieter aktualisieren",
    "REM": "REM",
    "Reset": "Zurücksetzen",
    "Reset API key": "API-Schlüssel zurücksetzen",
    "Reset key": "Schlüssel zurücksetzen",
    "Respiratory": "Atmung",
    "Respiratory rate": "Atemfrequenz",
    "Rest": "Ruhe",
    "Restart": "Neu starten",
    "Resting heart rate": "Ruheherzfrequenz",
    "Resting HR": "Ruhe-HF",
    "Restorative": "Erholsam",
    "Reveal in Finder": "Im Finder anzeigen",
    "ROUND": "RUNDE",
    "Running": "Läuft",
    "Save key": "Schlüssel speichern",
    "Save…": "Speichern…",
    "Saves every raw 5/MG frame (with a timestamp and the live heart rate) to a JSON file you can share to help map the biometric layout. This only records frames the strap already sent — it never writes to your strap — so it is safe to leave on. Export the file and attach it to a protocol-mapping issue.": "Speichert jeden rohen 5/MG-Frame (mit Zeitstempel und Live-Herzfrequenz) in einer JSON-Datei, die du teilen kannst, um das biometrische Layout zu kartieren. Dies zeichnet nur Frames auf, die der Strap bereits gesendet hat — es schreibt nie auf deinen Strap — daher ist es sicher, es aktiviert zu lassen. Exportiere die Datei und hänge sie an ein Protokoll-Mapping-Issue an.",
    "Scan": "Suchen",
    "Scan & Connect": "Suchen & Verbinden",
    "Scanning…": "Suche…",
    "Searching": "Suche",
    "SECONDS": "SEKUNDEN",
    "Send": "Senden",
    "Session": "Sitzung",
    "SESSION DONE": "SITZUNG FERTIG",
    "Session live": "Sitzung live",
    "Settings": "Einstellungen",
    "Sex": "Geschlecht",
    "Share of imported zone time, duration-weighted across sessions — approximate.": "Anteil der importierten Zonenzeit, zeitgewichtet über alle Einheiten — Näherungswert.",
    "Should you push today?": "Solltest du heute Gas geben?",
    "SIGNIFICANT": "SIGNIFIKANT",
    "Silent haptic HIIT — the strap buzzes the transitions": "Stilles haptisches HIIT — der Strap vibriert die Übergänge",
    "Skip for now": "Vorerst überspringen",
    "Sleep": "Schlaf",
    "Sleep Debt": "Schlafdefizit",
    "Sleep Performance": "Schlafleistung",
    "Slow threads": "Langsame Verläufe",
    "Source Apple Health": "Quelle Apple Health",
    "Source Whoop": "Quelle Whoop",
    "Stage breakdown": "Phasen-Aufschlüsselung",
    "Stages vs typical": "Phasen vs. typisch",
    "Start": "Start",
    "Start session": "Sitzung starten",
    "State": "Zustand",
    "Steps": "Schritte",
    "Stop session": "Sitzung beenden",
    "Strap": "Strap",
    "Strap bonded": "Strap gekoppelt",
    "STRAP LOG": "STRAP-PROTOKOLL",
    "Strap not connected": "Strap nicht verbunden",
    "Strap sync": "Strap-Sync",
    "Stress": "Stress",
    "Stress · M": "Stress · M",
    "Stress is derived from two autonomic signals.": "Stress wird aus zwei autonomen Signalen abgeleitet.",
    "Stress monitor": "Stress-Monitor",
    "Stress Trend": "Stress-Trend",
    "Support": "Support",
    "Support NOOP — donate or get in touch": "NOOP unterstützen — spenden oder Kontakt aufnehmen",
    "Support the build": "Die Entwicklung unterstützen",
    "Syncing strap history…": "Strap-Verlauf wird synchronisiert…",
    "Test action": "Aktion testen",
    "Test buzz": "Testvibration",
    "The thread of you over time.": "Dein Verlauf über die Zeit.",
    "These power your heart-rate zones, calorie estimates and recovery baselines. Keep them accurate.": "Diese steuern deine Herzfrequenzzonen, Kalorienschätzungen und Erholungs-Basislinien. Halte sie genau.",
    "Thinking": "Denkt nach",
    "This builds from the strap as it syncs. Strain and sleep appear after you have worn it and slept a night. Recovery needs about a week of nights to learn your baseline, or import your WHOOP export to skip the wait.": "Dies baut sich aus dem Strap auf, während er synchronisiert. Belastung und Schlaf erscheinen, nachdem du ihn getragen und eine Nacht geschlafen hast. Die Erholung braucht etwa eine Woche an Nächten, um deine Basislinie zu lernen, oder importiere deinen WHOOP-Export, um die Wartezeit zu überspringen.",
    "This stands on community reverse-engineering. Huge thanks:": "Dies basiert auf Reverse-Engineering der Community. Großen Dank:",
    "Time range": "Zeitbereich",
    "to": "bis",
    "Today": "Heute",
    "Today’s Synthesis": "Heutige Zusammenfassung",
    "Today's value is your recorded daily stress score (0–3).": "Der heutige Wert ist dein aufgezeichneter täglicher Stresswert (0–3).",
    "Total Calories": "Kalorien gesamt",
    "Total Distance": "Distanz gesamt",
    "Total Time": "Zeit gesamt",
    "Total Workouts": "Workouts gesamt",
    "Trend": "Trend",
    "Trends": "Trends",
    "Trends need history to draw. Import your WHOOP export — or connect Apple Health — in Data Sources to see weeks, months and years.": "Trends benötigen Verlauf zur Darstellung. Importiere deinen WHOOP-Export — oder verbinde Apple Health — unter Datenquellen, um Wochen, Monate und Jahre zu sehen.",
    "Try again": "Erneut versuchen",
    "Try WHOOP 5/MG protocol probes": "WHOOP 5/MG-Protokolltests ausprobieren",
    "Use": "Verwenden",
    "Use custom model": "Eigenes Modell verwenden",
    "Visual only": "Nur visuell",
    "Vital Signs": "Vitalwerte",
    "VO₂ Max": "VO₂max",
    "Wake at": "Aufwachen um",
    "We compare today's resting heart rate and HRV to your own 30-day baseline. A higher-than-usual resting HR and a lower-than-usual HRV both push the score up — classic signs the body is activated. The combined shift is mapped onto a 0–3 scale: 0 is calm, 1.5 sits at your baseline, 3 is highly activated.": "Wir vergleichen die heutige Ruheherzfrequenz und HRV mit deiner eigenen 30-Tage-Basislinie. Eine höhere Ruhe-HF als üblich und eine niedrigere HRV als üblich treiben den Wert beide nach oben — klassische Zeichen dafür, dass der Körper aktiviert ist. Die kombinierte Verschiebung wird auf eine Skala von 0–3 abgebildet: 0 ist ruhig, 1,5 liegt auf deiner Basislinie, 3 ist hoch aktiviert.",
    "Weight": "Gewicht",
    "What correlates": "Was korreliert",
    "WHAT TO EXPECT": "WAS DICH ERWARTET",
    "What's new": "Was ist neu",
    "When I double-tap": "Wenn ich doppelt tippe",
    "When the system prompt appears, choose Allow so NOOP can find your strap.": "Wenn die Systemabfrage erscheint, wähle „Erlauben“, damit NOOP deinen Strap finden kann.",
    "Which strap?": "Welcher Strap?",
    "Whoop": "Whoop",
    "Whoop import": "Whoop-Import",
    "WHOOP straps don't appear in macOS System Settings → Bluetooth. They advertise on a custom profile that only apps like NOOP can find — so there's nothing to pair there, and you shouldn't try.": "WHOOP-Straps erscheinen nicht in den macOS-Systemeinstellungen → Bluetooth. Sie senden über ein eigenes Profil, das nur Apps wie NOOP finden können — dort gibt es also nichts zu koppeln, und du solltest es nicht versuchen.",
    "Window": "Fenster",
    "With": "Mit",
    "Without": "Ohne",
    "Working…": "Arbeite…",
    "Workouts": "Workouts",
    "Wrist delivery isn't live yet — it needs a small on-device watcher (coming in an update) to read macOS notifications. Everything stays on this Mac. Your choices are saved now and will apply automatically once delivery ships.": "Die Zustellung ans Handgelenk ist noch nicht aktiv — sie benötigt einen kleinen Dienst auf dem Gerät (kommt in einem Update), um macOS-Mitteilungen zu lesen. Alles bleibt auf diesem Mac. Deine Auswahl ist jetzt gespeichert und wird automatisch angewendet, sobald die Zustellung verfügbar ist.",
    "You're connected.": "Du bist verbunden.",
    "Your live heart rate is working from the strap, and recovery, strain and sleep build from it over your next few nights of wear, sharpening as it learns your baseline. Want your full history instantly? Import your WHOOP export in Data Sources and it backfills in about a minute.": "Deine Live-Herzfrequenz funktioniert über den Strap, und Erholung, Belastung und Schlaf bauen sich daraus über deine nächsten Nächte des Tragens auf und werden schärfer, während er deine Basislinie lernt. Willst du sofort deine vollständige Historie? Importiere deinen WHOOP-Export unter Datenquellen, und er wird in etwa einer Minute nachgefüllt.",
    "Your numbers, your strap, and how NOOP works. All on this Mac.": "Deine Werte, dein Strap und wie NOOP funktioniert. Alles auf diesem Mac.",
    "Your strap in real time — heart rate and frames as they arrive.": "Dein Strap in Echtzeit — Herzfrequenz und Frames, sobald sie eintreffen.",
    "Your thread starts here.": "Dein Verlauf beginnt hier.",
    "Zone": "Zone",

    # FER-180 — «Today's metrics» intraday tile grid + MetricInfoSheet stress variant.
    "Today's metrics": "Heutige Werte",
    "vs yesterday": "ggü. gestern",
    "Same as yesterday": "Wie gestern",
    "Medium": "Mittel",
    "High": "Hoch",
    "Your autonomic load today, from 0 to 3. We estimate it by comparing today's resting heart rate and HRV with your own 30-day baseline: a higher-than-usual resting HR and a lower-than-usual HRV both push the number up — classic signs your body is activated.": "Deine autonome Belastung heute, von 0 bis 3. Wir schätzen sie, indem wir deinen heutigen Ruhepuls und deine HRV mit deiner eigenen 30-Tage-Basislinie vergleichen: ein höherer Ruhepuls als üblich und eine niedrigere HRV treiben den Wert nach oben — klassische Zeichen dafür, dass dein Körper aktiviert ist.",
    "Derived from your overnight resting heart rate and HRV — a transparent proxy for autonomic load, not a clinical stress measure.": "Abgeleitet aus deinem nächtlichen Ruhepuls und deiner HRV — ein transparenter Näherungswert für die autonome Belastung, kein klinisches Stressmaß.",
    "We take today's resting heart rate and HRV and express each as how far it sits from your 30-day average (a z-score). A resting HR above your norm and an HRV below it both add to the load; the two are summed and squashed onto a 0–3 scale where 0 is calm, 1.5 is your baseline, and 3 is highly activated.": "Wir nehmen deinen heutigen Ruhepuls und deine HRV und drücken jeden als Abstand zu deinem 30-Tage-Durchschnitt aus (einen z-Wert). Ein Ruhepuls über deiner Norm und eine HRV darunter erhöhen beide die Belastung; beide werden summiert und auf eine Skala von 0–3 gestaucht, wobei 0 ruhig, 1,5 deine Basislinie und 3 hoch aktiviert bedeutet.",
    "Combined resting-HR / HRV z-score through a logistic curve; HRV via RMSSD (Task Force, 1996).": "Kombinierter Ruhepuls-/HRV-z-Wert über eine logistische Kurve; HRV via RMSSD (Task Force, 1996).",

    # FER-145 — Langlebigkeit: «Körperalter» (Vitality + Body Age) und sein Detail.
    "Body age": "Körperalter",
    "years": "Jahre",
    "yrs": "J.",
    "you": "du",
    "The band, not the exact point, is the reading.": "Das Band, nicht der genaue Punkt, ist der Messwert.",
    "The same measure, 0–100:": "Dasselbe Maß, 0–100:",
    "· 50 = typical": "· 50 = typisch",
    "What's moving it": "Was es bewegt",
    "← rejuvenates you": "← verjüngt dich",
    "ages you →": "lässt dich altern →",
    "This isn't your Physical age": "Das ist nicht dein Fitnessalter",
    "Physical age measures only the cardiorespiratory side. This one also weighs sleep, regularity, HRV and steps — so the two can differ.": "Das Fitnessalter misst nur die kardiorespiratorische Seite. Dieses berücksichtigt auch Schlaf, Regelmäßigkeit, HRV und Schritte — daher können beide abweichen.",
    "A wellness comparison, not a biological age or a clinical diagnosis. HRV is estimated from nighttime PPG; the reference norm is conservative.": "Ein Vergleich des Wohlbefindens, kein biologisches Alter und keine klinische Diagnose. Die HRV wird aus nächtlichem PPG geschätzt; die Referenznorm ist konservativ.",
    "I need at least 3 signals to work this out without guessing. You have %lld.": "Ich brauche mindestens 3 Signale, um das ohne Raten zu berechnen. Du hast %lld.",
    "What it's built from": "Woraus es sich zusammensetzt",
    "Nighttime resting HR": "Nächtlicher Ruhepuls",
    "Sleep regularity": "Schlafregelmäßigkeit",
    "Regularity": "Regelmäßigkeit",
    "VO₂max": "VO₂max",
    "needs nights": "braucht Nächte",
    "needs valid nights": "braucht gültige Nächte",
    "connect Apple Health": "Apple Health verbinden",
    "ready": "bereit",
    "Keep wearing the band a few nights and it appears on its own — we don't show a half-finished number.": "Trag das Band ein paar Nächte und es erscheint von selbst — wir zeigen keine halbfertige Zahl.",
    "%lld years younger than your age (%lld)": "%lld Jahre jünger als dein Alter (%lld)",
    "%lld years older than your age (%lld)": "%lld Jahre älter als dein Alter (%lld)",
    "Right at your chronological age (%lld)": "Genau in deinem chronologischen Alter (%lld)",
    "rejuvenates you by %@ years": "verjüngt dich um %@ Jahre",
    "ages you by %@ years": "lässt dich um %@ Jahre altern",
    "neutral": "neutral",
    "Body age %lld, %lld years younger than your age %lld; estimated range %lld to %lld": "Körperalter %lld, %lld Jahre jünger als dein Alter %lld; geschätzter Bereich %lld bis %lld",
    "Body age %lld, %lld years older than your age %lld; estimated range %lld to %lld": "Körperalter %lld, %lld Jahre älter als dein Alter %lld; geschätzter Bereich %lld bis %lld",
    "Body age %lld, at your age %lld; estimated range %lld to %lld": "Körperalter %lld, in deinem Alter %lld; geschätzter Bereich %lld bis %lld",

    # Schlafdetail — «Instrumento»-Bildschirm, der die dunkle SleepView ersetzt (FER-212).
    "h asleep": "Std. geschlafen",
    "%@ · from Apple Health": "%@ · aus Apple Health",
    "Approximate stages": "Ungefähre Phasen",
    "Proportions, not minutes — the watch gets about 2 of 3 stages right.": "Anteile, keine Minuten — die Uhr trifft etwa 2 von 3 Phasen.",
    "Schedule regularity": "Regelmäßigkeit des Rhythmus",
    "How alike your mid-sleep point is night to night — it predicts your health better than total hours.": "Wie ähnlich dein Schlafmittelpunkt Nacht für Nacht ist — er sagt deine Gesundheit besser voraus als die Gesamtstunden.",
    "Weekend shift": "Wochenend-Verschiebung",
    "+%@ later": "+%@ später",
    "Still settling": "Pendelt sich noch ein",
    "Settling in · %lld nights to go": "Pendelt sich ein · noch %lld Nächte",
    "very regular": "sehr regelmäßig",
    "regular": "regelmäßig",
    "variable": "variabel",
    "Last night vs your typical": "Letzte Nacht vs. dein Üblich",
    "Duration trend": "Dauer-Trend",
    "Hours asleep per night · target band 7–9 h.": "Schlafstunden pro Nacht · Zielband 7–9 Std.",
    "Not enough nights yet to draw a trend.": "Noch nicht genug Nächte für einen Trend.",
    "%@ this week · one good night won't clear it.": "%@ diese Woche · eine gute Nacht gleicht es nicht aus.",
    "Tonight's metrics": "Werte der Nacht",
    "Performance": "Leistung",
    "vs your need": "vs. dein Bedarf",
    "−%@ vs your need": "−%@ vs. dein Bedarf",
    "vs time in bed": "vs. Zeit im Bett",
    "Restorative": "Erholsam",
    "Deep + REM": "Tief + REM",
    "Latency": "Latenz",
    "10–20 healthy": "10–20 gesund",
    "rpm": "AZ/min",
    "Awakenings": "Aufwachphasen",
    "times": "mal",
    "Regularity is the night-to-night variability of your mid-sleep point (the midpoint between falling asleep and waking) — a steadier schedule predicts health more strongly than how long you sleep. Stages are estimated from movement, heart rate and HRV, so they're approximate; deep sleep repairs the body, REM consolidates memory and emotion. \"Need\" is a 7–9 h population target, not a measurement of you.": "Regelmäßigkeit ist die nächtliche Schwankung deines Schlafmittelpunkts (der Mitte zwischen Einschlafen und Aufwachen) — ein gleichmäßigerer Rhythmus sagt die Gesundheit stärker voraus als die Schlafdauer. Phasen werden aus Bewegung, Herzfrequenz und HRV geschätzt, also ungefähr; Tiefschlaf repariert den Körper, REM festigt Gedächtnis und Emotionen. Der „Bedarf“ ist ein Bevölkerungsziel von 7–9 Std., keine Messung an dir.",
    "Windred et al., Sleep 2024 (regularity); Miller et al., J Sports Sci 2020 (wrist staging vs PSG); Hirshkowitz et al., 2015 (sleep need).": "Windred et al., Sleep 2024 (Regelmäßigkeit); Miller et al., J Sports Sci 2020 (Phasen am Handgelenk vs. PSG); Hirshkowitz et al., 2015 (Schlafbedarf).",
    "Source · Apple Health": "Quelle · Apple Health",
    "Source · your strap, on device": "Quelle · dein Band, auf dem Gerät",
    "No nights yet. Import your WHOOP export — or connect Apple Health — in Data Sources to see your sleep stages and trends. Or wear the strap to bed and open it again after the strap syncs.": "Noch keine Nächte. Importiere deinen WHOOP-Export — oder verbinde Apple Health — in Datenquellen, um deine Schlafphasen und Trends zu sehen. Oder trage das Band zum Schlafen und öffne es erneut, sobald das Band synchronisiert hat.",
    "Loading your sleep history…": "Lade deinen Schlafverlauf…",
    "Hours asleep per night, last 30 days": "Schlafstunden pro Nacht, letzte 30 Tage",
    "%@ – %@ · %lld%% efficiency": "%@ – %@ · %lld%% Effizienz",
    "%@, %lld%% last night": "%@, %lld%% letzte Nacht",
    ", typical %lld%%": ", üblich %lld%%",
    "+%lld pts": "+%lld Pkt.",
    "−%lld pts": "−%lld Pkt.",
    "−%@": "−%@",
    "Sleep stages: deep %lld percent, light %lld percent, REM %lld percent, awake %lld percent": "Schlafphasen: Tief %lld Prozent, Leicht %lld Prozent, REM %lld Prozent, Wach %lld Prozent",
    # FER-241 — Detalle de Estrés (Cuerpo)
    "Your autonomic load for the day: how activated your body is. We take today's resting heart rate and HRV, compare each with your own 30-day baseline as a z-score, and map the combined shift onto a 0–3 scale through a logistic curve (0 calm · 1.5 your baseline · 3 highly activated). It's an estimate, not a diagnosis.": "Deine autonome Belastung für den Tag: wie aktiviert dein Körper ist. Wir nehmen deinen heutigen Ruhepuls und deine HRV, vergleichen beide als z-Wert mit deiner eigenen 30-Tage-Basislinie und bilden die kombinierte Verschiebung über eine logistische Kurve auf eine Skala von 0–3 ab (0 ruhig · 1,5 deine Basislinie · 3 stark aktiviert). Es ist eine Schätzung, keine Diagnose.",
    "Information about stress": "Informationen zum Stress",
    "/ 3": "/ 3",
    "No stress reading yet. Wear your strap overnight and open this again after it syncs — or import your WHOOP history in Data Sources. Stress is read from your resting heart rate and HRV.": "Noch keine Stressmessung. Trage dein Band über Nacht und öffne dies erneut nach der Synchronisierung – oder importiere deinen WHOOP-Verlauf unter Datenquellen. Stress wird aus deinem Ruhepuls und deiner HRV abgeleitet.",
    "Each point is your daily stress index. The bands behind it are the fixed Low / Moderate / High zones (0–1 / 1–2 / 2–3). The percentage compares this month's average with last month's; Average, Lowest and Highest come from the range you selected. What matters isn't a single day — it's several days in a row drifting into a higher band.": "Jeder Punkt ist dein täglicher Stressindex. Die Bänder dahinter sind die festen Zonen Niedrig / Mittel / Hoch (0–1 / 1–2 / 2–3). Der Prozentsatz vergleicht den Durchschnitt dieses Monats mit dem des Vormonats; Durchschnitt, Tiefster und Höchster stammen aus dem gewählten Bereich. Entscheidend ist nicht ein einzelner Tag – sondern mehrere Tage in Folge, die in ein höheres Band rutschen.",
    "Information about the stress trend": "Informationen zum Stresstrend",
    "Daily stress index, 0 to 3": "Täglicher Stressindex, 0 bis 3",
    "Normal range": "Normalbereich",
    "These bands are the same for everyone because the index is already adjusted to your own baseline, not to the population — a 1.5 sits at YOUR normal. So there's no personal ± range to compute: what's worth watching is drifting into «High» for several days in a row.": "Diese Bänder sind für alle gleich, weil der Index bereits an deine eigene Basislinie angepasst ist, nicht an die Bevölkerung – eine 1,5 liegt bei DEINEM Normalwert. Deshalb gibt es keinen persönlichen ±-Bereich zu berechnen: zu beobachten ist, ob du mehrere Tage in Folge ins «Hoch» rutschst.",
    "· today": "· heute",
    "Stress rises when your resting heart rate runs higher than usual OR your HRV drops below usual — both are classic signs your nervous system is activated. We measure each against your own 30-day baseline. RMSSD for HRV (Task Force, 1996).": "Stress steigt, wenn dein Ruhepuls höher als üblich läuft ODER deine HRV unter das Übliche fällt – beides sind klassische Zeichen dafür, dass dein Nervensystem aktiviert ist. Wir messen beides gegen deine eigene 30-Tage-Basislinie. RMSSD für die HRV (Task Force, 1996).",
    "Information about what moves stress": "Informationen dazu, was Stress bewegt",
    "▲ +%lld": "▲ +%lld",
    "▼ −%lld": "▼ −%lld",
    "at base": "auf Basislinie",
    "below your base": "unter deiner Basislinie",
    "at your base": "auf deiner Basislinie",
    "Coefficient of variation = how spread out your daily stress is around its own average, as a percentage. Low = steady. A steadier signal usually means your load and recovery are in balance. (Plews 2013)": "Variationskoeffizient = wie stark dein täglicher Stress um seinen eigenen Durchschnitt streut, in Prozent. Niedrig = gleichmäßig. Ein gleichmäßigeres Signal bedeutet meist, dass Belastung und Erholung im Gleichgewicht sind. (Plews 2013)",
    "How steady your stress stays from one week to the next.": "Wie gleichmäßig dein Stress von einer Woche zur nächsten bleibt.",
    "The share of your recent days that sat in the Low band (under 1.0). Higher is better — it means your body had room to recover. It's a count of days, not a measure of how low any single day went.": "Der Anteil deiner letzten Tage, die im Band Niedrig lagen (unter 1,0). Höher ist besser – es bedeutet, dein Körper hatte Raum zur Erholung. Es ist eine Anzahl von Tagen, kein Maß dafür, wie niedrig ein einzelner Tag war.",
    "Information about calm time": "Informationen zur Ruhezeit",
    "How much of the last month you spent with low autonomic load.": "Wie viel des letzten Monats du mit niedriger autonomer Belastung verbracht hast.",
    "Stress by time of day": "Stress nach Tageszeit",
    "Coming soon, mapped against your calendar": "Bald verfügbar, abgeglichen mit deinem Kalender",
    "Soon": "Bald",
    "Stress by time of day, coming soon": "Stress nach Tageszeit, bald verfügbar",
    "We compare today's resting heart rate and HRV with your own 30-day baseline. A higher-than-usual resting HR and a lower-than-usual HRV both push the score up — classic signs the body is activated. The combined shift becomes a z-score sum, squashed onto 0–3 by a logistic curve: 0 calm, 1.5 at your baseline, 3 highly activated.": "Wir vergleichen deinen heutigen Ruhepuls und deine HRV mit deiner eigenen 30-Tage-Basislinie. Ein höherer Ruhepuls als üblich und eine niedrigere HRV als üblich treiben den Wert nach oben – klassische Zeichen dafür, dass der Körper aktiviert ist. Die kombinierte Verschiebung wird zu einer Summe von z-Werten, durch eine logistische Kurve auf 0–3 gestaucht: 0 ruhig, 1,5 auf deiner Basislinie, 3 stark aktiviert.",
    "Today's value is your recorded daily stress score (0–3). The trend, bands and markers are derived the same way.": "Der heutige Wert ist dein erfasster täglicher Stresswert (0–3). Trend, Bänder und Marker werden auf dieselbe Weise abgeleitet.",
    "Combined resting-HR / HRV z-score through a logistic curve. HRV via RMSSD (Task Force, 1996). An estimate, not a diagnosis.": "Kombinierter z-Wert aus Ruhepuls / HRV über eine logistische Kurve. HRV via RMSSD (Task Force, 1996). Eine Schätzung, keine Diagnose.",
    # FER-241 — claves compartidas que en de seguían en inglés (las usa esta pantalla + Recuperación/vitales)
    "Stable this month": "Diesen Monat stabil",
    "steady": "gleichmäßig",
}


def main() -> int:
    # encoding="utf-8" is load-bearing: without it Windows defaults to cp1252 and a run
    # mojibakes every umlaut in the catalog (empirically: 82 German strings corrupted).
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    strings = catalog["strings"]

    missing: list[str] = []
    for key, entry in strings.items():
        if not key:
            continue
        de = DE.get(key)
        if de is None:
            missing.append(key)
            continue
        locs = entry.setdefault("localizations", {})
        locs["de"] = {"stringUnit": {"state": "translated", "value": de}}

    CATALOG.write_text(json.dumps(catalog, indent=2, ensure_ascii=False) + "\n",
                       encoding="utf-8")

    translated = sum(
        1 for k, v in strings.items()
        if k and "de" in v.get("localizations", {})
    )
    print(f"German units written: {translated}")
    if missing:
        print(f"MISSING ({len(missing)}):")
        for k in missing:
            print("  " + repr(k))
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
